defaults: &defaults
  docker:
    - image: circleci/golang:1.10
  working_directory: /go/src/github.com/ernoaapa/linuxkit-server

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      
      # Some of the tests requires that there's docker running
      - setup_remote_docker
      
      - run: "! go fmt -l pkg cmd 2>&1 | read"
      - run: go vet ./...
      - run: go test -v ./...
  
  build:
    <<: *defaults
    steps:
      - checkout

      - setup_remote_docker

      - run: go get github.com/goreleaser/goreleaser
      - run: goreleaser --snapshot

  publish:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Login Docker hub
          command: echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin

      - run: 
          name: Install tools
          command: |
            go get github.com/goreleaser/goreleaser
            go get github.com/estesp/manifest-tool
      - run: goreleaser
      - run: |
          VERSION=$(git describe --tags --always --dirty)
          manifest-tool \
            --username ${DOCKER_USER} \
            --password ${DOCKER_PASS} \
            push from-args \
            --platforms linux/amd64,linux/arm64 \
            --template ernoaapa/linuxkit-server:${VERSION}-ARCH \
            --target ernoaapa/linuxkit-server:${VERSION}

workflows:
  version: 2
  build_and_test:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
              
      - build:
          requires:
            - test
          filters:
            tags:
              only: /.*/

      - publish:
          requires:
            - test
            - build
          
          # Don't run when branches updates, only when tags get created
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /v.*/
